user.get = SELECT id, username, password FROM public."user" WHERE id=?;
user.getAll = SELECT id, username, password, createdAt FROM public."user";
user.insert = INSERT INTO public.\"user\"(\n\tid, username, password, \"createdAt\")\n\tVALUES (?, ?, ?, ?);
user.update = UPDATE public.\"user\"SET id=?, username=?, password=?, \"createdAt\"=? WHERE id=?;
user.delete = DELETE FROM public.\"user\" WHERE id=?;

order.get = SELECT id, user_id, order_status, createdat, totalprice FROM public.\"order\" WHERE id=?;
order.getAll  = SELECT id, user_id, order_status, createdat, totalprice FROM public.\"order\";
order.insert  = INSERT INTO public.\"order\"(user_id, order_status, createdat, totalprice) VALUES (?, ?, ?, ?);
order.update  = UPDATE public.\"order\" SET id=?, user_id=?, order_status=?, createdat=?, totalprice=? WHERE <condition>;
order.delete  = DELETE FROM public.\"order\" WHERE id=?;

dish.get = SELECT * FROM dish WHERE id = ?;
dish.getAll = SELECT * FROM dish;
dish.insert = INSERT INTO dish(name, description, price, category, is_available) VALUES (?, ?, ?, ?, ?);
dish.update = UPDATE dish SET id=?, name=?, description=?, price=?, category=?, is_available=? WHERE id=?;
dish.delete = DELETE FROM dish WHERE id = ?;