user.get = SELECT id, username, password, role FROM users WHERE id=?;
user.getByUsername = SELECT id, username, password, role FROM users WHERE username=?;
user.getAll = SELECT id, username, password, role FROM users;
user.insert = INSERT INTO users(username, password, role) VALUES (?, ?, ?);
user.update = UPDATE users SET id=?, username=?, password=?, role=? WHERE id=?;
user.delete = DELETE FROM users WHERE id=?;

order.get = SELECT o.id AS order_id, o.status AS order_status, o.created_at, \
u.id as user_id, username, password, role, \
t.id AS table_id, table_number, t.status AS table_status \
FROM orders o JOIN users u ON o.user_id = u.id \
JOIN cafe_table t on o.table_id = t.id \
WHERE o.id=?;
order.getAll  = SELECT o.id AS order_id, o.status AS order_status, o.created_at, u.id as user_id, username, password, role, t.id AS table_id, table_number, t.status AS table_status FROM orders o JOIN users u ON o.user_id = u.id JOIN cafe_table t on o.table_id = t.id;
order.insert  = INSERT INTO orders(table_id, user_id, status, created_at) VALUES (?, ?, ?, ?);
order.update  = UPDATE orders SET id=?, table_id=?, user_id=?, status=?, created_at=? WHERE id=?;
order.delete  = DELETE FROM orders WHERE id=?;

dish.get = SELECT * FROM dish WHERE id = ?;
dish.getAll = SELECT * FROM dish;
dish.insert = INSERT INTO dish(name, description, price, category, is_available) VALUES (?, ?, ?, ?, ?);
dish.update = UPDATE dish SET id=?, name=?, description=?, price=?, category=?, is_available=? WHERE id=?;
dish.delete = DELETE FROM dish WHERE id = ?;

orderItem.get = SELECT ot.id as order_item_id, ot.quantity, ot.comment, \
o.id as order_id, o.table_id, o.user_id, o.status, o.created_at, \
d.id as dish_id, d.name, d.description, d.price, d.category, d.is_available, \
u.username, u.password, u.role, t.table_number, t.status \
FROM order_item ot \
JOIN orders o ON ot.order_id = o.id \
JOIN dish d ON ot.dish_id = d.id \
JOIN users u on o.user_id = u.id \
JOIN cafe_table t ON o.table_id = t.id \
WHERE ot.id = ?;
orderItem.getAll = SELECT ot.id as order_item_id, ot.quantity, ot.comment, \
o.id as order_id, o.table_id, o.user_id, o.status AS order_status, o.created_at, \
d.id as dish_id, d.name AS dish_name, d.description, d.price, d.category, d.is_available, \
u.username, u.password, u.role, t.table_number, t.status AS table_status \
FROM order_item ot \
JOIN orders o ON ot.order_id = o.id \
JOIN dish d ON ot.dish_id = d.id \
JOIN users u on o.user_id = u.id \
JOIN cafe_table t ON o.table_id = t.id;
orderItem.getByOrderId = SELECT ot.id as order_item_id, ot.quantity, ot.comment, \
o.id as order_id, o.table_id, o.user_id, o.status AS order_status, o.created_at, \
d.id as dish_id, d.name AS dish_name, d.description, d.price, d.category, d.is_available, \
u.username, u.password, u.role, t.table_number, t.status AS table_status \
FROM order_item ot \
JOIN orders o ON ot.order_id = o.id \
JOIN dish d ON ot.dish_id = d.id \
JOIN users u on o.user_id = u.id \
JOIN cafe_table t ON o.table_id = t.id WHERE order_id = ?;
orderItem.insert = INSERT INTO order_item(id, order_id, dish_id, quantity, comment) VALUES (?, ?, ?, ?, ?);
orderItem.update = UPDATE order_item SET id=?, order_id=?, dish_id=?, quantity=?, comment=? WHERE id=?;
orderItem.delete = DELETE FROM order_item WHERE id=?;

table.get = SELECT id, table_number, status FROM cafe_table WHERE id = ?;
table.getAll = SELECT id, table_number, status FROM cafe_table;
table.insert = INSERT INTO cafe_table(id, table_number, status) VALUES (?, ?, ?);
table.update = UPDATE cafe_table SET id=?, table_number=?, status=? WHERE id=?;
table.delete = DELETE FROM cafe_table WHERE id=?;